// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TunesAPI;

namespace TunesAPI.Migrations
{
    [DbContext(typeof(TunesContext))]
    [Migration("20190321161009_TunesTwo")]
    partial class TunesTwo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TunesAPI.Tunes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Album");

                    b.Property<string>("AlbumCoverLink");

                    b.Property<string>("Artist");

                    b.Property<string>("BuyLink");

                    b.Property<string>("Duration");

                    b.Property<string>("Genre");

                    b.Property<int>("GlobalChart");

                    b.Property<int>("IrishChart");

                    b.Property<double>("Price");

                    b.Property<DateTime>("Realsed");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Tunes");
                });
#pragma warning restore 612, 618
        }
    }
}
