// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TunesAPI;

namespace TunesAPI.Migrations
{
    [DbContext(typeof(TunesContext))]
    partial class TunesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TunesAPI.Tunes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Album");

                    b.Property<string>("AlbumCoverLink");

                    b.Property<string>("Artist");

                    b.Property<string>("BuyLink");

                    b.Property<string>("Duration");

                    b.Property<string>("Genre");

                    b.Property<int>("GlobalChart");

                    b.Property<int>("IrishChart");

                    b.Property<double>("Price");

                    b.Property<DateTime>("Realsed");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Tunes");

                    b.HasData(
                        new { Id = 1, Album = "Thriller", AlbumCoverLink = "https://upload.wikimedia.org/wikipedia/en/thumb/5/55/Michael_Jackson_-_Thriller.png/220px-Michael_Jackson_-_Thriller.png", Artist = "Michael Jackson", BuyLink = "https://www.amazon.com/Thriller-Michael-Jackson/dp/B00VSHH9GC/ref=tmm_acd_swatch_0?_encoding=UTF8&qid=1552692547&sr=8-1", Duration = "5.58", Genre = "Pop", GlobalChart = 0, IrishChart = 1, Price = 9.16, Realsed = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Thriller" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
